# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=3)),
                ('language', models.CharField(max_length=20)),
                ('editor', models.CharField(blank=True, max_length=50)),
                ('is_second_hand', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Bookshops',
        ),
        migrations.RemoveField(
            model_name='food',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.AddField(
            model_name='books',
            name='bookshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Bookshops'),
        ),
    ]
